[package]
name = "tui-app"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
humantime = "2.2.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
rusqlite = { version = "0.34.0", features = ["bundled"] }
